# Numpy Notebook
## Introduction

This notebook is on [NumPy](http://www.numpy.org/). NumPy is the fundamental package for scientific computing in Python. It allows you to analyze data more effectively than the standard python package. I will use a brief example to show how it can simply Multiplication of two Matrices. 

## Exampel Standard Python Multiplication of two Matrices

In [5]:

# input two matrices of size n x m 
matrix1 = [[1, 6, 5], 
        [3 ,4, 8], 
        [2, 12, 3]] 
matrix2 = [[3, 4, 6], 
        [5, 6, 7], 
        [6,56, 7]] 
  
res = [[0 for x in range(3)] for y in range(3)]  
  
# explicit for loops 
for i in range(len(matrix1)): 
    for j in range(len(matrix2[0])): 
        for k in range(len(matrix2)): 
  
            # resulted matrix 
            res[i][j] += matrix1[i][k] * matrix2[k][j] 
  
print (res) 

[[63, 320, 83], [77, 484, 102], [84, 248, 117]]


## Using Numpy Multiplication of two Matrices

In [6]:
# We need install numpy in order to import it 
import numpy as np 
  
# input two matrices 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
  
# This will return dot product 
res = np.dot(mat1,mat2) 
  
# print resulted matrix 
print(res)

[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


As you can see the results are the same, but the code used in NumPy is far easier for a human to read.